### ISSUE TITLE
Failed to activate the coffeedocs package

### ISSUE THREAD

**Issue by camjc** [maschs/coffeedocs#4]
Package doesn't load in atom 1.0 preview mode. `atom --one` in the commandline

**Atom Version**: 0.199.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10
**Thrown From**: [coffeedocs](https://github.com/maschs/coffeedocs) package, v0.8.2

### Stack Trace

Failed to activate the coffeedocs package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/Users/Cam/.atom/packages/coffeedocs/lib/main.coffee:16:23)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:219:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:211:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:435:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:345:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:41:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -7:34.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:52.3.0 core:select-all (atom-text-editor.editor.mini.is-focused)
  4x -6:51.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -6:04.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -6:03.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:58.3.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -4:57.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -4:29.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -0:33.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:32.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:32.3.0 pane:show-previous-item (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.2
coffee-porter, v0.1.0
coffeedocs, v0.8.2
language-coffee-script-angular, v2.2.0
linter, v0.12.2
linter-coffeelint, v0.2.3
linter-csslint, v0.0.12
linter-doiuse, v0.2.3
linter-jshint, v0.1.4
linter-stylint, v0.5.1
linter-tidy, v1.0.1
linter-write-good, v0.4.3
npm-autocomplete, v0.1.2
path, v0.4.1

# Dev
No dev packages
```

**Comment by maschs** [comment]
Should be fixed now.
